### ISSUE TITLE
error in network.tf terraform module

### ISSUE THREAD

**Issue by mvasilenko** [GSA/devsecops-example#30]
I'm trying to follow your setup as described in README,

got an error while running `terraform init`

```
Error getting plugins: module root: module network: aws_region is not a valid parameter
```

which is caused by line `aws_region = "${data.aws_region.current.name}"` in `network.tf`
When this line is commented out, `terraform init` passes successfully

Terraform v0.10.6

**Comment by afeld** [comment]
Hey, sorry for the slow response. Mind trying again on the latest `master`?

**Comment by afeld** [comment]
Closing for now, but feel free to re-open if you're still having the issue.
