### ISSUE TITLE
Still some jenkins cleanup

### ISSUE THREAD

**Issue by Vermyndax** [GSA/devsecops-example#66]
There's still a jenkins.json packer template and jenkins.yml file. I probably should have requested that those get deleted in the PR, but I just noticed them while looking at EKK stack integration.

**Comment by afeld** [comment]
Pretty sure I got everything...you're looking at the latest `master`?

**Comment by Vermyndax** [comment]
Yeah, looks like my git didn't kill the files when I refreshed. My bad!
