### ISSUE TITLE
ensure content is persistent across deploys

### ISSUE THREAD

**Issue by afeld** [GSA/devsecops-example#7]
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html?icmpid=docs_ec2_console
* https://d0.awsstatic.com/whitepapers/wordpress-best-practices-on-aws.pdf
* http://www.sanjeevnandam.com/blog/ec2-mount-ebs-volume-during-launch-time
* https://github.com/hashicorp/terraform/issues/2740#issuecomment-288549352

## Likely steps

* [x] Determine what folders in WordPress should be considered mutable
* [ ] Mutable WordPress content is saved on its own volume(s)
* [ ] Volume(s) are seamlessly reattached to the new instance after a deploy

## Acceptance criteria

* [ ] Content from before a deploy is present after a deploy

**Comment by Vermyndax** [comment]
/<wordpress-root>/wp-content/* is considered mutable
